name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  nix:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - runs-on: unbuntu-latest
            system: aarch64-darwin
          - runs-on: macos-latest
            system: x86_64-linux
      fail-fast: false
    steps:
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: install om
        run: |
          nix --accept-flake-config profile install github:juspay/omnix
      - uses: actions/checkout@v4
      - name: om show
        run: om show .
      - name: om ci
        run: om ci run --extra-access-tokens "github.com=${{ secrets.GITHUB_TOKEN }}" --systems "${{ matrix.system }}"
      - name: om init tests
        run: |
          om init --test .
